### ISSUE TITLE
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 10 * NSEC_PER_SEC), dispatch_get_main_queue(), printBlock);

### ISSUE THREAD

**Issue by lilongcnc** [HuolalaTech/hll-wp-glog#14]
有个点不解，烦请大佬解惑。Benchmark项目中，`loganWrite`和`glogWriteAsync`中都有
`dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 10 * NSEC_PER_SEC), dispatch_get_main_queue(), printBlock);`
这句代码，为什么要延迟10s获取存储的内容大小呢？是有什么坑吗？ 是有几率write完后马上read，会有机率读不到刚才 write 的内容吗？

**Comment by mricefox** [comment]
当前异步写入没有 idle callback, 为了读取到完整日志大小，粗暴的方式是 delay 一段时间确保写入完成; 实际使用中，如果在写入过程中进行读取，会对日志文件进行快照处理，不会影响写入。
