### ISSUE TITLE
文档和注释有点简陋，so包体积有点大

### ISSUE THREAD

**Issue by w290721955** [HuolalaTech/hll-wp-glog#16]
文档和注释有点简陋，希望补充下。so库包体积比logan大太多，希望增加裁剪功能。

**Comment by mricefox** [comment]
so 体积偏大主要是因为集成了 STL 库，如果项目中已经包含 libc++_shared.so 可以使用 `implementation 'cn.huolala.glog.android:glog-android-shared:1.0.1' ` 来缩减包体积
