### ISSUE TITLE
直接上传 glog 文件到后端，解析的问题。

### ISSUE THREAD

**Issue by lilongcnc** [HuolalaTech/hll-wp-glog#19]
请问下货拉拉的上传方式是直接上传文件到服务端吗？还是说读取内容之后再上传呢？
如果前者的话，有后端的解析部分是否可以公开下呢？

**Comment by mricefox** [comment]
在我们的监控系统中，实时日志、离线日志对日志文件的读取有不同时机；读取日志的相关代码：https://github.com/HuolalaTech/hll-wp-glog/tree/master/Misc

**Comment by lilongcnc** [comment]
是我大意了，没看全库 Orz
