### ISSUE TITLE
归档时间

### ISSUE THREAD

**Issue by liqy** [HuolalaTech/hll-wp-glog#22]
如何调整归档时间按小时统计

**Comment by mricefox** [comment]
按日增量归档的日志每 2 分钟会尝试归档 [源码](https://github.com/HuolalaTech/hll-wp-glog/blob/744e4eb9ad948d48f010931c81e1d15c8fd34200/Core/Glog.cpp#L100) ; 如果这样仍然解决不了你的问题，可以通过在上层定时调用 [Glog::flush()](https://github.com/HuolalaTech/hll-wp-glog/blob/744e4eb9ad948d48f010931c81e1d15c8fd34200/Core/Glog.h#L86) 来实现。
