### ISSUE TITLE
关于 flush 时机

### ISSUE THREAD

**Issue by lilongcnc** [HuolalaTech/hll-wp-glog#26]
如果是实时归档的话，就需要开发自己调用flush方法来归档，但是我发现每次调用 flush 的时候，都会导致帧率下降，如果是频繁的 flush 的话，卡顿更加明显。应该是 flush 操作会占用相当部分的cpu资源。  目前我设置的是每15条执行 flush 一次，想问下你们是否遇到 flush时卡顿的问题，怎么处理的呢？或者flush导致的卡顿从底层库的角度可以优化掉呢？

**Comment by mricefox** [comment]
针对增量按天归档的日志类型，Glog 内部有一个[守护线程](https://github.com/HuolalaTech/hll-wp-glog/blob/c319695324d1e9b9186a5bcc5e5a48d5dd075c6b/Core/Glog.cpp#L61)每 2 分钟会自动 flush 一次；如果需要非常频繁的归档，可以尝试在子线程中调用 flush
