### ISSUE TITLE
为啥设置 expireSeconds、totalArchiveSizeLimit 后不生效

### ISSUE THREAD

**Issue by Robust28LSL** [HuolalaTech/hll-wp-glog#27]
为啥设置 expireSeconds、totalArchiveSizeLimit 后不生效，还是一直往一个文件里面写。怎么限制每个文件的大小，和写入文件时间。我设置每个文件1M超过1M还是往里面写入。

**Comment by lilongcnc** [comment]
测试看起来他是以文件为删除单位的。 两个文件，一共1M，会删除其中一个。只有一个，貌似不会删除。

**Comment by Robust28LSL** [comment]
支持增量(按天)归档和全量(按文件)归档； 
这个key需要怎么设置，怎么用啊

**Comment by mricefox** [comment]
> 为啥设置 expireSeconds、totalArchiveSizeLimit 后不生效，还是一直往一个文件里面写。怎么限制每个文件的大小，和写入文件时间。我设置每个文件1M超过1M还是往里面写入。

清理文件是每 2 分钟自动进行的，[参考代码](https://github.com/HuolalaTech/hll-wp-glog/blob/c319695324d1e9b9186a5bcc5e5a48d5dd075c6b/Core/Glog.cpp#L756) 无论是增量、全量归档，只有一个归档文件时，这个文件是不会被删除的，这是因为这个文件可能正在被处理，通常来说是从 mmap 缓存中 flush 日志。这里也没有通过锁机制来隔离 flush 和清理操作，这主要是考虑到日志的写入性能。

**Comment by mricefox** [comment]
> 支持增量(按天)归档和全量(按文件)归档； 这个key需要怎么设置，怎么用啊

不知道你说的是哪个 key ，Glog 需要设置的加密 key 是 ECC 公钥，密钥对生成方式[参考](https://github.com/HuolalaTech/hll-wp-glog/blob/c319695324d1e9b9186a5bcc5e5a48d5dd075c6b/Misc/generate-ecc-key.py)，注意保存私钥用于解密。

**Comment by Robust28LSL** [comment]
> > 为啥设置 expireSeconds、totalArchiveSizeLimit 后不生效，还是一直往一个文件里面写。怎么限制每个文件的大小，和写入文件时间。我设置每个文件1M超过1M还是往里面写入。
> 
> 清理文件是每 2 分钟自动进行的，[参考代码](https://github.com/HuolalaTech/hll-wp-glog/blob/c319695324d1e9b9186a5bcc5e5a48d5dd075c6b/Core/Glog.cpp#L756) 无论是增量、全量归档，只有一个归档文件时，这个文件是不会被删除的，这是因为这个文件可能正在被处理，通常来说是从 mmap 缓存中 flush 日志。这里也没有通过锁机制来隔离 flush 和清理操作，这主要是考虑到日志的写入性能。

我指的不是删掉，比如我日志文件每个想设置成1M，文件达到1M之后，不能自动往下一个文件里写吗。
我的意思生成的日志存在多个文件

**Comment by mricefox** [comment]
> > > 为啥设置 expireSeconds、totalArchiveSizeLimit 后不生效，还是一直往一个文件里面写。怎么限制每个文件的大小，和写入文件时间。我设置每个文件1M超过1M还是往里面写入。
> > 
> > 
> > 清理文件是每 2 分钟自动进行的，[参考代码](https://github.com/HuolalaTech/hll-wp-glog/blob/c319695324d1e9b9186a5bcc5e5a48d5dd075c6b/Core/Glog.cpp#L756) 无论是增量、全量归档，只有一个归档文件时，这个文件是不会被删除的，这是因为这个文件可能正在被处理，通常来说是从 mmap 缓存中 flush 日志。这里也没有通过锁机制来隔离 flush 和清理操作，这主要是考虑到日志的写入性能。
> 
> 我指的不是删掉，比如我日志文件每个想设置成1M，文件达到1M之后，不能自动往下一个文件里写吗。 我的意思生成的日志存在多个文件

暂时不支持设置单个文件大小阈值

**Comment by lilongcnc** [comment]
@Robust28LSL 你可以执行15条就flush 一下，控制单个文件大小
