### ISSUE TITLE
libglog.so与rn依赖的glog库产生冲突。

### ISSUE THREAD

**Issue by Madezhedoubeizhuce** [HuolalaTech/hll-wp-glog#28]
和rn（react-native-0.64.2）一起使用时报错：Caused by: com.android.builder.merge.DuplicateRelativeFileException: More than one file was found with OS independent path 'lib/armeabi-v7a/libglog.so'。
[err.txt](https://github.com/HuolalaTech/hll-wp-glog/files/12461655/1.txt)

**Comment by mricefox** [comment]
目前我们还没有遇到过这个问题，你可以对[源码](https://github.com/HuolalaTech/hll-wp-glog/blob/master/Android/glog/CMakeLists.txt)进行修改，重命名 lib 之后，发布到私有仓库使用。
