### ISSUE TITLE
No variants found for ':glog'

### ISSUE THREAD

**Issue by qi5945** [HuolalaTech/hll-wp-glog#29]
![image](https://github.com/HuolalaTech/hll-wp-glog/assets/7687285/45cb26a8-9444-4ba6-8cfb-da361cf43aeb)

**Comment by qi5945** [comment]
运行Android工程，提示No variants found for ':glog'

**Comment by mricefox** [comment]
是怎么操作的呢？运行了什么 gradle 命令
