### ISSUE TITLE
关于压缩率的疑问

### ISSUE THREAD

**Issue by porum** [HuolalaTech/hll-wp-glog#30]
- 关闭pb+开启aes，分别测试写入1w和10w条日志，测试压缩效率：

![Screenshot_2023-12-12-15-51-15-018_glog android sample](https://github.com/HuolalaTech/hll-wp-glog/assets/48167317/b4a035e3-e851-4d38-80b2-cfbdb83588d6)

- 关闭pb+关闭aes，分别测试写入1w和10w条日志，测试压缩效率：

![Screenshot_2023-12-12-15-57-15-724_glog android sample](https://github.com/HuolalaTech/hll-wp-glog/assets/48167317/40364e65-e082-44fb-ba5b-8a8774085765)

发现开启aes加密后，日志文件体积比原始数据要大的多，快接近1倍了！即使关闭加密，日志文件体积也跟原始数据相差不大。

所以想请教一下 @mricefox  glog 在实际使用中的压缩效率如何？

**Comment by mricefox** [comment]
[使用 AES 加密时，在每条日志前都写入了 AES IV + ECC public key](https://github.com/HuolalaTech/hll-wp-glog/blob/616a949363ce5be9e673faa38eab43cb6ee153f1/Core/Glog_IO.cpp#L45)，总计 80 bytes, 在单条日志原始数据较短的情况下，由于压缩算法的限制，压缩率不高，经过压缩、加密之后日志体积反而会有一定增量。
