### ISSUE TITLE
npm打包生成的electron app，拖拽.glog文件进去后没有任何反应

### ISSUE THREAD

**Issue by captain-Lu** [HuolalaTech/hll-wp-glog#32]
录屏如下：

https://github.com/HuolalaTech/hll-wp-glog/assets/20471187/dbe51889-3c6d-438e-aff3-a69d5a4ca8ef

**Comment by mricefox** [comment]
方便把日志文件发一下吗

**Comment by captain-Lu** [comment]
日志
[log-20240603.glog.zip](https://github.com/user-attachments/files/15543088/log-20240603.glog.zip)

**Comment by mricefox** [comment]
写入日志如果没有用 protobuf 序列化，可直接用 Plain Text 模式解码
![image](https://github.com/user-attachments/assets/b2e0df17-936c-4061-b658-80793485720f)
