### ISSUE TITLE
更新xcode15.4后，运行项目报错。  No template named 'function' in namespace 'std'

### ISSUE THREAD

**Issue by captain-Lu** [HuolalaTech/hll-wp-glog#33]
问题：更新xcode15.4后，运行项目报错。
错误提示： No template named 'function' in namespace 'std'
错误位置：`bool writeLogData(const GlogBuffer &data, const std::function<bool(uint32_t length)> &insufficientSpaceCallback);`
临时解决方案：通过头部引入#include <functional>可解决，但对于cocoapod集成的项目不友好，麻烦作者更新一下

**Comment by mricefox** [comment]
fix #34

**Comment by lilongcnc** [comment]
@mricefox 得打个tag吧
