### ISSUE TITLE
异步写入不担心丢日志吗

### ISSUE THREAD

**Issue by simonla** [HuolalaTech/hll-wp-glog#5]

**Comment by mricefox** [comment]
根据线上日志来看，出现这种情况非常极端；可以开启同步写入模式来避免这种问题，但是性能会有所下降

**Comment by simonla** [comment]
> 根据线上日志来看，出现这种情况非常极端；可以开启同步写入模式来避免这种问题，但是性能会有所下降

那性能对比的部分挺容易让人误解的

**Comment by mricefox** [comment]
后续会提供 c++ 层的序列化支持，在此基础上做进一步的性能对比
