### ISSUE TITLE
glog initialize failed

### ISSUE THREAD

**Issue by yorkvolvo** [HuolalaTech/hll-wp-glog#8]
# Error
glog initialize failed

 java.lang.UnsatisfiedLinkError: No implementation found for void glog.android.Glog.jniInitialize(int) (tried Java_glog_android_Glog_jniInitialize and Java_glog_android_Glog_jniInitialize__I)

#
是否可以分享一些关于 Glog 使用的 demo 或者文章，或者一些 api 文档？

**Comment by mricefox** [comment]
请提供你的使用方式；文章参考 https://juejin.cn/post/7168662263337861133/
