### ISSUE TITLE
异步模式下丢日志的case处理

### ISSUE THREAD

**Issue by chengxumiaodaren** [HuolalaTech/hll-wp-glog#9]
Xlog有一个亮点是异步模式下通过mmap做缓存，假如应用crash，下次启动时会继续把这段缓存的内容读出来持久化。
这样减少了丢日志的可能性，看hll glog的文档原理介绍中貌似没有这个功能？可以考虑完善下。

**Comment by mricefox** [comment]
mmap 在 crash 之后能够更有效的将日志回写磁盘，这个写入的时机并不是发生在应用重启之后，可以参考微信的相关文章 [微信终端跨平台组件 mars 系列（一） - 高性能日志模块xlog](https://mp.weixin.qq.com/s/cnhuEodJGIbdodh0IxNeXQ?)；Glog 底层也是使用 mmap I/O ，在同步模式下，如果发生 crash ，回写能力与 xlog 一致
